local Card = require("src.cards.card")
local StandardDeck = require("src.decks.standard")

local function newCard(rank, desc)
    local card = Card.new("yellow", rank, desc)
    StandardDeck.register(card)
end

newCard(0, {name = "Yellow Zero", desc = "A standard yellow zero. Also acts as 10, going after 9 and before Reverse."})
newCard(0, {name = "Yellow Ace", desc = "A standard yellow ace. Goes both before 2 and after Draw."})
newCard(0, {name = "Yellow Two", desc = "A standard yellow two."})
newCard(0, {name = "Yellow Three", desc = "A standard yellow three."})
newCard(0, {name = "Yellow Four", desc = "A standard yellow four."})
newCard(0, {name = "Yellow Five", desc = "A standard yellow five."})
newCard(0, {name = "Yellow Six", desc = "A standard yellow six."})
newCard(0, {name = "Yellow Seven", desc = "A standard yellow seven."})
newCard(0, {name = "Yellow Eight", desc = "A standard yellow eight."})
newCard(0, {name = "Yellow Nine", desc = "A standard yellow nine."})
newCard(0, {name = "Yellow Reverse", desc = "A standard yellow reverse. When the highest played card, the direction of play reverses."})
newCard(0, {name = "Yellow Skip", desc = "A standard yellow skip. When the highest played card, the next player is skipped."})
newCard(0, {name = "Yellow Draw Two", desc = "A standard yellow draw two. When the highest played card, the next player draws two cards and is skipped."})